export const APP_INITILIZING = 'APP_INITILIZING';

export const USER_GENERATIONS = 'USER_GENERATIONS';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const CLEAR_IMAGE = 'CLEAR_IMAGE';
export const USER_SELECTED_IMAGE = 'USER_SELECTED_IMAGE';
export const DELETE_USER_SELECTED_IMAGE = 'DELETE_USER_SELECTED_IMAGE';
export const CLEAR_USER_SELECTED_IMAGE = 'CLEAR_USER_SELECTED_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const STORE_IMAGE_LIST = 'STORE_IMAGE_LIST';

export const SELECTED_RESULT = 'SELECTED_RESULT';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const SYNC_JOBS = 'SYNC_JOBS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';
export const UPDATE_JOB_STATUS = 'UPDATE_JOB_STATUS';
export const DELETE_JOB = 'DELETE_JOB';
export const RUNNING_JOB = 'RUNNING_JOB';

export const TRACKING_JOB = 'TRACKING_JOB';
export const TRACKING_JOB_SUCCESS = 'TRACKING_JOB_SUCCESS';
export const TRACKING_JOB_ERROR = 'TRACKING_JOB_ERROR';

export const ADD_JOB_DATA = 'ADD_JOB_DATA';
export const UPDATE_JOB_DATA = 'UPDATE_JOB_DATA';
export const ADD_MODEL_IMAGES = 'ADD_MODEL_IMAGES';
export const ADD_STYLE_IMAGE = 'ADD_STYLE_IMAGE';
export const ADD_MODEL_TYPE = 'ADD_MODEL_TYPE';
export const ADD_STYLE_TYPE = 'ADD_STYLE_TYPE';
export const ADD_LOCATION = 'ADD_LOCATION';

export const ADD_PHOTOAI_STYLE = 'ADD_PHOTOAI_STYLE';
export const ADD_PHOTOAI_MODEL = 'ADD_PHOTOAI_MODEL';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REMEMBER_ME = 'REMEMBER_ME';

export const USER_PAYMENTS = 'USER_PAYMENTS';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const CLEAR_CREDITS = 'CLEAR_CREDITS';
